# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='parent_post',
            new_name='parent',
        ),
    ]
