# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255, verbose_name='Board Name')),
                ('slug', models.SlugField(max_length=10, verbose_name='URL Slug')),
                ('info', models.TextField(blank=True, verbose_name='Board info and rules')),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
            },
        ),
    ]
